#!/bin/sh

usage()
{
    cat<<USAGE
    options are:
        -h          show this help menu
        -l          list all users with a failed login count of at least 1
        -r [user]   reset [user] failed login count and unlocks them.  ALL will unlock all users
        -s          only show your own failed login count
USAGE
}

list()
{
    lsuser -R LDAP -a unsuccessful_login_count ALL 2>/dev/null | grep -vE '=0$'
    lsuser -a unsuccessful_login_count ALL 2>/dev/null | grep -vE '=0$'
}

reset()
{
    if [ "x$1" = xALL ]; then
        for user in $(lsuser -R LDAP -a unsuccessful_login_count ALL 2>/dev/null | grep -vE '=0$' | awk '{ print $1 }'); do
            echo "resetting login count for $user"
            chsec -f /etc/security/lastlog -a 'unsuccessful_login_count=0' -s "$user" 2>/dev/null
        done
        for user in $(lsuser -R LDAP -a account_locked ALL 2>/dev/null | grep 'true' | awk '{ print $1 }'); do
            echo "unlocking $user"
            chuser 'account_locked=false' "$user" 2>/dev/null
        done
        for user in $(lsuser -a unsuccessful_login_count ALL 2>/dev/null | grep -vE '=0$' | awk '{ print $1 }'); do
            echo "resetting login count for $user"
            chsec -f /etc/security/lastlog -a 'unsuccessful_login_count=0' -s "$user" 2>/dev/null
        done
        for user in $(lsuser -a account_locked ALL 2>/dev/null | grep 'true' | awk '{ print $1 }'); do
            echo "unlocking $user"
            chuser 'account_locked=false' "$user" 2>/dev/null
        done
    else
        echo "resetting login count for $1"
        chsec -f /etc/security/lastlog -a 'unsuccessful_login_count=0' -s "$1" 2>/dev/null
        echo "unlocking $1"
        chuser 'account_locked=false' "$1" 2>/dev/null
    fi
}

show()
{
    lsuser -a unsuccessful_login_count "$1" 2>/dev/null || lsuser -R LDAP -a unsuccessful_login_count "$1" 2>/dev/null
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

while getopts 'hlr:s:' opt; do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        l)
            list
            ;;
        r)
            reset "$OPTARG"
            ;;
        s)
            show "$OPTARG"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done
